# Generated by Django 3.2 on 2021-04-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=10)),
                ('document_type', models.CharField(max_length=5)),
                ('number_document', models.IntegerField(verbose_name=12)),
                ('phone', models.CharField(max_length=12)),
                ('email_adrres', models.CharField(max_length=30)),
                ('addres', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('user_client', models.CharField(max_length=20)),
                ('password_client', models.CharField(max_length=20)),
            ],
        ),
    ]
