# Generated by Django 3.2 on 2021-04-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('sex', models.CharField(max_length=10)),
                ('document_type', models.CharField(max_length=5)),
                ('number_document', models.IntegerField(verbose_name=12)),
                ('email_adrres', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('user_instructor', models.CharField(max_length=20)),
                ('password_instructor', models.CharField(max_length=20)),
            ],
        ),
    ]
