# Generated by Django 3.2 on 2021-04-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
