# Generated by Django 3.2 on 2021-04-15 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gruaduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruaduated',
            name='id_instructor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.instructor'),
        ),
        migrations.AddField(
            model_name='gruaduated',
            name='name_enterprise',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gruaduated',
            name='time_enterprise',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
