# Generated by Django 3.2 on 2021-04-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210415_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruaduated',
            name='id_instructor',
        ),
    ]
