# Generated by Django 3.2 on 2021-04-15 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gruaduated_id_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruaduated',
            name='id_instructor',
        ),
    ]
