# Generated by Django 3.2 on 2021-04-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_gruaduated_id_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruaduated',
            name='id_instructor',
            field=models.IntegerField(default=None, max_length=10000000),
            preserve_default=False,
        ),
    ]
