# Generated by Django 3.2 on 2021-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_gruaduated_id_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gruaduated',
            name='available',
        ),
        migrations.RemoveField(
            model_name='gruaduated',
            name='time_enterprise',
        ),
        migrations.AddField(
            model_name='gruaduated',
            name='academic_training',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gruaduated',
            name='program_name',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
