# Generated by Django 3.2.1 on 2021-05-07 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210421_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id_review', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('menssage', models.CharField(max_length=100)),
                ('id_instructor', models.IntegerField(default=0)),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.gruaduated')),
            ],
        ),
    ]
